# Dependencies
markdown:         kramdown
kramdown:
  input:          GFM
gems:
                  - jekyll-sitemap

# Permalinks
permalink:        /:year/:month/:day/:title

# Setup
title:            Spuer xing
description:      '<a href="https://twitter.com/lebornjose" target="_blank">@lebornjose</a>'
baseurl:          /
url:              http://blog.leborn.me
domain:           leobrn.me
email:            lebornjose@gmail.com
twitter_username: leborn
github_username:  lebornjose
timezone:         China/ShangHai
subscribe:        http://feed.ztpala.com
exclude:          [ README.md, newpost.rb, CNAME ]

author:
  url:            https://twitter.com/lebornjose

paginate:         5

github:
  repo:           https://github.com/lebornjose/blog
